---
- name: Add IP to phpIPAM
  hosts: all
  gather_facts: no
  vars:
    ipam: '{{ ipam_server }}'
    phpipam_api_url: "https://{{ ipam }}/api/myapp"  # Update with your API URL
    phpipam_token: "your_api_token_here"              # Replace with your API token

  tasks:
    - name: Add IP address to phpIPAM
      uri:
        url: "{{ phpipam_api_url }}/addresses/"
        method: POST
        headers:
          Content-Type: "application/json"
          token: "{{ phpipam_token }}"
        body: |
          {
            "ip": "{{ variable_ip }}",
            "hostname": "{{ variable_host }}"
          }
        body_format: json
        return_content: yes
      register: result

    - name: Display response
      debug:
        var: result.json
