---
- name: Check if VM name exists in MariaDB and send email if not
  hosts: localhost
  gather_facts: false
  collections:
    - community.mysql
    - community.general  # For the mail module
  vars:
    hostname: "hostname"
  tasks:
    - name: Write VM details to MariaDB
      community.mysql.mysql_query:
        login_host: "aap.tbs.lab"    # Replace with your MariaDB host
        login_user: "root"    # Replace with your MariaDB user
        login_password: ".root"  # Replace with your MariaDB password
        login_db: "vm_inventory"
        query: |
          INSERT INTO vm_details (name, memory_mb, num_vcpus, ip_address, requestor_name)
          VALUES ("{{ hostname }}", 4096, 2, "192.168.1.1", "vladimir.todorov@tbs.tech");