---
- name: Check if VM name exists in MariaDB and send email if not
  hosts: localhost
  gather_facts: false
  collections:
    - community.mysql
    - community.general  # For the mail module
  vars:
    hostname: "{{ variable_host }}"
    requestorname: "{{ variable_requestor }}"
  tasks:
    - name: Check if VM name exists in MariaDB
      community.mysql.mysql_query:
        login_host: "10.10.10.11"    # Replace with your MariaDB host
        login_user: "{{ lookup('env', 'DB_USERNAME') }}"    # Replace with your MariaDB user
        login_password: "{{ lookup('env', 'DB_PASSWORD') }}"  # Replace with your MariaDB password
        login_db: "{{ lookup('env', 'DB_NAME') }}"
        query: |
          SELECT COUNT(*) AS count FROM vm_details WHERE name = "{{ hostname }}";
      register: vm_check_result
      delegate_to: localhost

    - name: Debug query result
      debug:
        var: vm_check_result

    - name: VM exist
      debug:
        msg: "The VM name '{{ hostname }}' already exists in the database."
        msg: vm_check_result.query_result[0].count
      when: vm_check_result.query_result[0].count | int > 0

    - name: VM name does not exist
      debug:
        msg: "The VM name '{{ hostname }}' doesnot exists in the database."
        msg: vm_check_result.query_result[0].count
      when: vm_check_result.query_result[0].count | int == 0