---
- name: Check if VM name exists in MariaDB
  hosts: localhost
  gather_facts: no
  vars:
    hostname: "{{ variable_host }}"
    requestorname: "{{ variable_requestor }}"
    db_host: "127.0.0.1"        # MariaDB host
    db_user: "your_user"        # MariaDB username
    db_password: "your_password"  # MariaDB password
    db_name: "vm_inventory"     # Database name
    vm_name_to_check: "MyVM"    # VM name to check

  tasks:
    - name: Check if the VM name exists in the database
      community.mysql.mysql_query:
        login_host: "10.10.10.11"
        login_user: "{{ lookup('env', 'DB_USERNAME') }}"
        login_password: "{{ lookup('env', 'DB_PASSWORD') }}"
        login_db: "{{ lookup('env', 'DB_NAME') }}"
        query: "SELECT COUNT(*) AS vm_count FROM vm_details WHERE name = '{{ hostname }}';"
      register: vm_check_result


    - name: Inspect the full structure of vm_check_result
      debug:
        var: vm_check_result

    - name: Debug the result if VM exists
      debug:
        msg: "VM name '{{ vm_name_to_check }}' exists in the database."
      when: vm_check_result.query_result[0]["vm_count"] > 0  # Adjust based on debug output

    - name: Debug the result if VM does not exist
      debug:
        msg: "VM name '{{ vm_name_to_check }}' does not exist in the database."
      when: vm_check_result.query_result[0]["vm_count"] == 0  # Adjust based on debug output