---
- name: VM playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ lookup('env', 'PRISM_CENTRAL_URL') }}"
      nutanix_username: "{{ lookup('env', 'PRISM_CENTRAL_USERNAME') }}"
      nutanix_password: "{{ lookup('env', 'PRISM_CENTRAL_PASSWORD') }}"
      validate_certs: false
  vars:
    hostname:  "AnsibleDemo"
    hostip:  "192.168.1.1"
    num_vcpus:  "1"
    memory_mb:  "2"
    requestor_name:  "vladimir.todorov@tbs.tech"
    vm_os: "Rocky 9.4 minimal"
  tasks:
  - name: Debug the rewritten vm_os value
    debug:
      msg: "The updated vm_os is: {{ vm_os }}"
        
  - name: Setting Variables
    set_fact:
        cluster_name: "CLS"
        script_path: ""
        subnet_name: 'TBS\|TEST\|Generic-44'
        image_name: "{{ vm_os }}"
        password: "12345678"
        fqdn: ""

  - name: Create Cloud-init Script file
    copy:
      dest: "cloud_init.yml"
      content: |
         #cloud-config
         chpasswd:
           list: |
             root: "{{ password }}"
             expire: False
         fqdn: "{{ fqdn }}"

  - name: create Vm
    ntnx_vms:
      state: present
      name: "{{ hostname }}"
      desc: "ansible_automation_demo"
      categories:
        AppType:
          - "Apache_Spark"
      cluster:
        name: "{{cluster_name}}"
      networks:
        - is_connected: True
          subnet:
            name: "{{ subnet_name }}"
            # mention cluster only when there are multiple subnets with same name accross clusters
            # and subnet name is set above
            cluster:
              name: "{{cluster_name}}"
      disks:
        - type: "DISK"
          size_gb: 40
          bus: "SATA"
          clone_image:
            name: "{{ image_name }}"
      vcpus: 1
      cores_per_vcpu: 1
      memory_gb: 1
      guest_customization:
        type: "cloud_init"
        script_path: "./cloud_init.yml"
        is_overridable: True
    register: output

  - name: output of vm created
    debug:
      msg: '{{ output }}'

 # - name: delete VM
 #   ntnx_vms:
 #     state: absent
 #     vm_uuid: "{{output.vm_uuid}}"
