---
- name: VM playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ lookup('env', 'PRISM_CENTRAL_URL') }}"
      nutanix_username: "{{ lookup('env', 'PRISM_CENTRAL_USERNAME') }}"
      nutanix_password: "{{ lookup('env', 'PRISM_CENTRAL_PASSWORD') }}"
      validate_certs: false
  vars:
    hostname:  "AnsibleDemo"
    hostip:  "192.168.1.1"
    num_vcpus:  "1"
    memory_mb:  "2"
    requestor_name:  "vladimir.todorov@tbs.tech"
    vm_os: "Windows Server 2022 Eval-v1"
    ip_address: "192.168.1.1"
    netmask: "255.255.255.0"
    gateway: "192.168.1.1"
    dns_servers: "192.168.173.101"
  tasks:
  - name: Debug the rewritten vm_os value
    debug:
      msg: "The updated vm_os is: {{ vm_os }}"
        
  - name: Setting Variables
    set_fact:
        cluster_name: "CLS"
        script_path: ""
        subnet_name: 'TBS\|TEST\|Generic-44'
        image_name: "{{ vm_os }}"
        password: "12345678"
        fqdn: ""

  - name: Create Cloud-init Script file
    copy:
      dest: "cloud_init.yml"
      content: |
         #cloud-config
         chpasswd:
           list: |
             root: "{{ password }}"
             expire: False
         fqdn: "{{ fqdn }}"
  - name: Determine if the VM OS is Linux or Windows
    set_fact:
      is_linux: "{{ 'linux' in vm_os.lower() }}"
      is_windows: "{{ 'windows' in vm_os.lower() }}"
      
  - name: Set boot type and customization method
    set_fact:
      boot_type: "{{ 'UEFI' if is_windows else 'LEGACY' | trim }}"
      customization_type: "{{ 'sysprep' if is_windows else 'cloud_init' | trim }}"

  - name: Debug boot_type
    debug:
      msg: "The boot type is set to {{ boot_type }}"

  - name: create Vm
    ntnx_vms:
      state: present
      name: "{{ hostname }}"
      desc: "ansible_automation_demo"
      categories:
        AppType:
          - "Apache_Spark"
      cluster:
        name: "{{cluster_name}}"
      networks:
        - is_connected: True
          subnet:
            name: "{{ subnet_name }}"
            cluster:
              name: "{{cluster_name}}"
          static_ip: "{{ ip_address }}"  # Assign static IP here              
      disks:
        - type: "DISK"
#          size_gb: 40
          bus: "SCSI"
          clone_image:
            name: "{{ image_name }}"
      vcpus: 1
      cores_per_vcpu: 1
      memory_gb: 1
      boot_config:
        boot_type: "{{ boot_type }}"
      guest_customization:
        type: "{{ customization_type }}"
        script_path: "./{{ customization_type }}.yml"
        is_overridable: True
    register: output

  - name: output of vm created
    debug:
      msg: '{{ output }}'

 # - name: delete VM
 #   ntnx_vms:
 #     state: absent
 #     vm_uuid: "{{output.vm_uuid}}"
