---
- name: Write to MariaDB (CMDB)
  hosts: localhost
  gather_facts: false
  collections:
    - community.mysql
    - community.general  # For the mail module
  vars:
    hostname:  "{{ variable_hostname }}"
    hostip:  "{{ variable_pass }}"
    requestor_name:  "{{ variable_requestor }}"
    num_vcpus:  '{{ variable_vcpus }}'
    memory_mb:  '{{ variable_vram }}'
  tasks:
    - name: Write VM details to MariaDB
      community.mysql.mysql_query:
        login_host: "{{ lookup('env', 'DB_HOST') }}"    # Replace with your MariaDB host
        login_user: "{{ lookup('env', 'DB_USERNAME') }}"    # Replace with your MariaDB user
        login_password: password  # Replace with your MariaDB password
        login_db: "vm_inventory"
        login_port: "{{ lookup('env', 'DB_PORT') }}"
        query: |
          INSERT INTO vm_details (name, memory_mb, num_vcpus, ip_address, requestor_name)
          VALUES ("{{ hostname }}", "{{ memory_mb }}", "{{ num_vcpus }}", "{{ hostip }}", "{{ requestor_name }}");