---
- name: Write to MariaDB (CMDB)
  hosts: localhost
  gather_facts: false
  collections:
    - community.mysql
    - community.general  # For the mail module
  vars:
    hostname:  "{{ variable_hostname }}"
    hostip:  "{{ variable_pass }}"
  tasks:
    - name: Write VM details to MariaDB
      community.mysql.mysql_query:
        login_host: "10.10.10.11"    # Replace with your MariaDB host
        login_user: "{{ lookup('env', 'DB_USERNAME') }}"    # Replace with your MariaDB user
        login_password: password  # Replace with your MariaDB password
        login_db: "vm_inventory"
        query: |
          INSERT INTO vm_details (name, memory_mb, num_vcpus, ip_address, requestor_name)
          VALUES ("{{ hostname }}", 4096, 2, "{{ hostip }}", "vladimir.todorov@tbs.tech");