---
- name: Send email to approver
  hosts: localhost
  gather_facts: no
  vars:
    approver_email: '{{ variable_user }}'
    request_number: "12345"
    smtp_server: "smtp.office365.com"
    smtp_port: 587
    smtp_username: '{{ variable_user }}'
    smtp_password: '{{ variable_pass }}'
  tasks:
    - name: Send email to approver
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        sender: "{{ smtp_username }}"
        to:
          - "{{ approver_email }}"
        subject: "Please approve request number {{ request_number }}"
        body: |
          Dear Approver,

          Please approve request number {{ request_number }}.

          Best regards,
          Automation System
        secure: starttls