---
- name: Send email to approver
  hosts: localhost
  gather_facts: no
  vars:
    approver_email: "{{ lookup('env', 'SMTP_USERNAME') }}"
    request_number: "12345"
    smtp_server: "{{ lookup('env', 'SMTP_SERVER') }}"
    smtp_port: "{{ lookup('env', 'SMTP_PORT') | int }}"
    smtp_username: "{{ lookup('env', 'SMTP_USERNAME') }}"
    smtp_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
    hostname:  '{{ variable_hostname }}'
    hostip:  "{{ variable_pass }}"
    num_vcpus:  '{{ variable_vcpus }}'
    memory_mb:  '{{ variable_vram }}'
    requestor_name:  "{{ variable_requestor }}"
  tasks:
    - name: Send email to approver
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        sender: "{{ smtp_username }}"
        to:
          - "{{ approver_email }}"
        subject: "Please approve request number {{ request_number }}"
        body: |
          Dear approver, 
          Please approve the following request:

          - **Hostname**: {{ hostname }}
          - **CPU**: {{ num_vcpus }} vCPUs
          - **Memory**: {{ memory_mb }} MB
          - **Requestor**: {{ requestor_name }}

          Kindly review the details and proceed with the approval.

          Best regards,
          Your Automation System

        secure: starttls