---
- name: Send email to approver
  hosts: localhost
  gather_facts: no
  vars:
    approver_email: "{{ lookup('env', 'SMTP_USERNAME') }}"
    request_number: "12345"
    smtp_server: "{{ lookup('env', 'SMTP_SERVER') }}"
    smtp_port: "{{ lookup('env', 'SMTP_PORT') | int }}"
    smtp_username: "{{ lookup('env', 'SMTP_USERNAME') }}"
    smtp_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
  tasks:
    - name: Send email to approver
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        sender: "{{ smtp_username }}"
        to:
          - "{{ approver_email }}"
        subject: "Please approve request number {{ request_number }}"
        body: |
          Dear Approver,

          Please approve request number {{ request_number }}.

          Best regards,
          Automation System
         secure: "{{ 'starttls' if lookup('env', 'USE_TLS') | bool else 'none' }}"